---
site_name: Friday Gemini AI
docs_dir: docs
nav:
  - Home: index.md
  - Start:
      - Quickstart: start/quickstart.md
  - Guides:
      - Community: guides/community.md
      - Development: guides/development.md
      - Practices: guides/practices.md
      - Resources: guides/resources.md
      - Troubleshooting: guides/troubleshoot.md
      - Workflows: guides/workflows.md
  - Reference:
      - API: reference/api.md
      - Architecture: reference/architecture.md
      - Capabilities: reference/capabilities.md
      - Cookbook: reference/cookbook.md
      - HarperBot: reference/harperbot.md
      - Models: reference/models.md
      - Testing: reference/testing.md
      - Usage: reference/usage.md
      - Versions: reference/versions.md
  - Additional:
      - Changelog: CHANGELOG.md
      - Contributing: CONTRIBUTING.md
      - Code of Conduct: CODE_OF_CONDUCT.md
      - Security: SECURITY.md
      - Setup: SETUP.md
